name: Deploy Kobweb to Vercel

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '25'

      - name: Dar permissão de execução ao Gradle Wrapper
        run: chmod +x gradlew

      - name: Compilar e Exportar o site Kobweb
        run: ./gradlew kobwebExport -Pkobweb.export.layout=STATIC

      - name: Deploy para a Vercel
        run: |
          npm install -g vercel@latest
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: .kobweb/site/system